const SUPABASE_URL = String(window.CLIMATE_CONFIG?.SUPABASE_URL || "").replace(/\/$/, "");
const SUPABASE_PUBLISHABLE_KEY = String(window.CLIMATE_CONFIG?.SUPABASE_PUBLISHABLE_KEY || "");
const API_URL = SUPABASE_URL ? `${SUPABASE_URL}/functions/v1/climate-api` : "";
const climateMeta=[{id:"tropical",name:"열대",icon:"🌴"},{id:"dry",name:"건조",icon:"🏜️"},{id:"temperate",name:"온대",icon:"🌳"},{id:"continental",name:"냉대",icon:"🌲"},{id:"polar",name:"한대",icon:"❄️"},{id:"alpine",name:"고산",icon:"🏔️"}];
const titles={dashboard:"수업 현황",ranking:"탐험 랭킹",students:"학생별 결과",climates:"기후별 분석",questions:"문제별 분석",settings:"수업 설정"};
let token=sessionStorage.getItem("climateTeacherToken")||"";let currentClass="";let dashboard={rows:[],summary:{},climateStats:[],classes:[],settings:{}};let activeTab="dashboard";let refreshTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function time(s){s=Math.max(0,Math.round(Number(s)||0));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function toast(m){const x=$('#admin-toast');x.textContent=m;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2500)}
async function api(action,data={}){if(!API_URL||!SUPABASE_PUBLISHABLE_KEY)throw new Error("config.js에 Supabase 연결 정보를 먼저 설정하세요.");const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({action,token,...data})});const j=await r.json().catch(()=>({success:false,message:`서버 응답 오류 (${r.status})`}));if(!r.ok||!j.success){if(j.code==="AUTH_REQUIRED")logout(false);throw new Error(j.message||"요청 실패")}return j.data}
function statusFor(r){const vals=Object.values(r.climateScores||{}).filter(v=>v!==null&&v!=="").map(Number);const low=vals.filter(v=>v<60).length;if(r.accuracy>=80&&low===0)return ["✅ 이해 양호",""];if(r.accuracy>=60&&low<2)return ["🔎 다시 확인 필요","review"];return ["📘 보충 학습 권장","support"]}
function table(rows,clickable=true){if(!rows.length)return '<div class="empty">표시할 학생 결과가 없습니다.</div>';return `<div class="table-wrap"><table><thead><tr><th>순위</th><th>학생</th><th>점수</th><th>정답률</th><th>첫 시도</th><th>탐험지역</th><th>시간</th><th>학습 상태</th></tr></thead><tbody>${rows.map(r=>{const st=statusFor(r);return `<tr ${clickable?`class="clickable" data-session="${esc(r.gameSessionId)}"`:''}><td class="rank-medal">${r.rank<=3?["🥇","🥈","🥉"][r.rank-1]:r.rank||'-'}</td><td>${esc(r.className)} ${String(r.studentNumber).padStart(2,'0')} · ${esc(r.nickname)}</td><td class="score">${r.explorationScore}점</td><td>${Math.round(r.accuracy)}%</td><td>${r.firstTryCorrect}/${r.totalQuestions}</td><td>${(r.visitedClimates||[]).length}</td><td>${time(r.playTime)}</td><td><span class="status ${st[1]}">${st[0]}</span></td></tr>`}).join('')}</tbody></table></div>`}
function bars(stats){return stats.map(s=>`<div class="bar-row"><span>${s.icon||''} ${esc(s.name)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(s.average)||0))}%"></i></div><b>${s.count?Math.round(s.average)+'%':'-'}</b></div>`).join('')||'<div class="empty">분석할 결과가 없습니다.</div>'}

async function login(pin){$('#login-error').textContent='';try{const d=await api('verifyTeacherPin',{pin});token=d.token;sessionStorage.setItem("climateTeacherToken",token);$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadDashboard();startRefresh()}catch(e){$('#login-error').textContent=e.message}}
function logout(show=true){token="";sessionStorage.removeItem("climateTeacherToken");clearInterval(refreshTimer);$('#app-view').classList.add('hidden');$('#login-view').classList.remove('hidden');if(show)toast("로그아웃했습니다.")}
function startRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(!document.hidden&&activeTab!=="settings")loadDashboard(false)},30000)}
async function loadDashboard(notify=true){
  const btn=$('#refresh');btn.disabled=true;try{dashboard=await api('getDashboard',{className:currentClass});renderAll();if(notify)toast("최신 결과를 불러왔습니다.")}catch(e){showNotice(e.message,true)}finally{btn.disabled=false}
}
function showNotice(msg,error=false){const n=$('#notice');n.textContent=msg;n.style.background=error?'#ffeaeb':'#e8f6f4';n.style.color=error?'#a8323a':'#136a5a';n.classList.remove('hidden')}
function renderAll(){renderClassOptions();renderDashboard();renderRanking();renderStudents();renderClimates();fillSettings()}
function renderClassOptions(){const select=$('#class-filter'),old=currentClass;select.innerHTML='<option value="">전체 학급</option>'+dashboard.classes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');select.value=old}
function renderDashboard(){
  const s=dashboard.summary||{};$('#summary-cards').innerHTML=[["참여 학생",`${s.participants||0}명`],["게임 완료",`${s.completed||0}명`],["평균 탐험 점수",`${Math.round(s.averageScore||0)}점`],["평균 정답률",`${Math.round(s.averageAccuracy||0)}%`],["평균 플레이 시간",time(s.averagePlayTime||0)]].map(x=>`<div class="summary-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
  $('#recent-table').innerHTML=table((dashboard.rows||[]).slice(0,5));$('#dashboard-climates').innerHTML=bars(dashboard.climateStats||[]);const h=(dashboard.climateStats||[]).filter(x=>x.count).sort((a,b)=>a.average-b.average)[0];$('#hardest-card').innerHTML=h?`<h2>⚠️ 추가 설명이 필요한 영역</h2><p><strong>${h.icon} ${esc(h.name)} 기후</strong> · 학급 평균 정답률 <b>${Math.round(h.average)}%</b></p><p>${esc(h.guidance)}</p>`:'<h2>⚠️ 추가 설명이 필요한 영역</h2><p>분석할 결과가 아직 없습니다.</p>'
}
function sortedRows(){let a=[...(dashboard.rows||[])],mode=$('#rank-sort').value;const f={score:(x,y)=>y.explorationScore-x.explorationScore||y.firstTryCorrect-x.firstTryCorrect||y.accuracy-x.accuracy,accuracy:(x,y)=>y.accuracy-x.accuracy,firstTry:(x,y)=>y.firstTryCorrect-x.firstTryCorrect,playTime:(x,y)=>x.playTime-y.playTime,number:(x,y)=>x.studentNumber-y.studentNumber,recent:(x,y)=>new Date(y.completedAt)-new Date(x.completedAt)};a.sort(f[mode]);return a}
function renderRanking(){const a=sortedRows();let rank=0,last='';a.forEach((r,i)=>{const k=`${r.explorationScore}-${r.firstTryCorrect}-${r.accuracy}`;if(k!==last)rank=i+1;r.rank=rank;last=k});$('#ranking-table').innerHTML=table(a)}
function renderStudents(){const q=$('#student-search').value.trim().toLowerCase();const rows=(dashboard.rows||[]).filter(r=>!q||String(r.studentNumber).includes(q)||String(r.nickname).toLowerCase().includes(q));$('#student-table').innerHTML=table(rows)}
function renderClimates(){const stats=dashboard.climateStats||[];$('#climate-bars').innerHTML=bars(stats);const h=stats.filter(s=>s.count).sort((a,b)=>a.average-b.average)[0];$('#climate-guidance').innerHTML=h?`<h2>수업 피드백</h2><p class="overline">LOWEST AREA</p><h3>${h.icon} ${esc(h.name)} 기후 · ${Math.round(h.average)}%</h3><p>${esc(h.guidance)}</p>`:'<h2>수업 피드백</h2><p>학생 결과가 쌓이면 자동으로 안내합니다.</p>'}
function fillSettings(){const s=dashboard.settings||{};const f=$('#settings-form');f.elements.rankingEnabled.checked=String(s.rankingEnabled)!=='false';['rankingLimit','rankingMode','nameMode','questionCount','regionCount','bossCount'].forEach(k=>{if(s[k]!=null)f.elements[k].value=String(s[k])})}
async function loadQuestions(){const box=$('#question-grid');box.innerHTML='<p>분석 중...</p>';try{const d=await api('getQuestionStats',{className:currentClass});box.innerHTML=d.length?d.map(q=>`<div class="question-card"><h3>${esc(q.questionId)} <small>${esc(q.climate)}</small></h3><b class="big">${Math.round(q.accuracy)}%</b><p>첫 시도 정답률 · 응답 ${q.total}명</p><p><b>가장 많이 선택한 오답</b><br>${esc(q.topWrong||'선택된 오답 없음')} ${q.topWrongCount?`(${q.topWrongCount}명)`:''}</p></div>`).join(''):'<div class="empty">문제 응답 데이터가 없습니다.</div>'}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function openStudent(sessionId){const dlg=$('#student-dialog'),box=$('#student-detail');box.innerHTML='<p>학생 결과를 불러오는 중...</p>';dlg.showModal();try{const r=await api('getStudentResult',{gameSessionId:sessionId});const good=[],review=[];climateMeta.forEach(c=>{const v=r.climateScores?.[c.id];if(v==null)return;(v>=75?good:review).push(`${c.name} 기후 ${v}%`)});box.innerHTML=`<div class="detail-head"><p class="overline">STUDENT INSIGHT</p><h2>${esc(r.className)} ${r.studentNumber}번 · ${esc(r.nickname)}</h2></div><div class="detail-stats"><div class="detail-stat"><small>탐험 점수</small><b>${r.explorationScore}점</b></div><div class="detail-stat"><small>정답률</small><b>${Math.round(r.accuracy)}%</b></div><div class="detail-stat"><small>첫 시도</small><b>${r.firstTryCorrect}/${r.totalQuestions}</b></div><div class="detail-stat"><small>플레이 시간</small><b>${time(r.playTime)}</b></div></div><h3>기후별 결과</h3>${bars(climateMeta.map(c=>({name:c.name,icon:c.icon,average:r.climateScores?.[c.id]||0,count:r.climateScores?.[c.id]!=null?1:0})))}<div class="feedback-box"><b>📘 교사용 참고</b><p><b>잘 이해한 내용</b><br>${good.length?good.map(x=>'• '+x+'의 핵심 개념을 잘 이해하고 있습니다.').join('<br>'):'• 아직 충분한 데이터가 없습니다.'}</p><p><b>다시 확인하면 좋은 내용</b><br>${review.length?review.map(x=>'• '+x+' 관련 자연환경과 생활의 관계를 다시 확인해 보세요.').join('<br>'):'• 모든 탐험 기후를 잘 이해했습니다.'}</p></div>`}catch(e){box.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function switchTab(name){activeTab=name;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab').forEach(t=>t.classList.toggle('active',t.id===`tab-${name}`));$('#page-title').textContent=titles[name];if(name==='questions')loadQuestions()}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function downloadCsv(){const rows=dashboard.rows||[];const head=['학급','번호','별명','점수','정답률','첫 시도 정답','기후별 결과','플레이 시간','업적'];const lines=[head,...rows.map(r=>[r.className,r.studentNumber,r.nickname,r.explorationScore,r.accuracy,`${r.firstTryCorrect}/${r.totalQuestions}`,climateMeta.map(c=>`${c.name}:${r.climateScores?.[c.id]??'-'}`).join(' | '),time(r.playTime),(r.achievements||[]).join(' | ')])].map(row=>row.map(csvCell).join(','));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`기후탐험대_${currentClass||'전체'}_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}

$('#login-form').addEventListener('submit',e=>{e.preventDefault();login($('#pin').value)});$('#logout').addEventListener('click',()=>logout());$('#refresh').addEventListener('click',()=>loadDashboard());$('#class-filter').addEventListener('change',e=>{currentClass=e.target.value;loadDashboard()});$('#rank-sort').addEventListener('change',renderRanking);$('#student-search').addEventListener('input',renderStudents);$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)switchTab(b.dataset.tab)});document.addEventListener('click',e=>{const g=e.target.closest('[data-goto]');if(g)switchTab(g.dataset.goto);const row=e.target.closest('[data-session]');if(row)openStudent(row.dataset.session)});$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s={rankingEnabled:f.elements.rankingEnabled.checked,rankingLimit:Number(f.elements.rankingLimit.value),rankingMode:f.elements.rankingMode.value,nameMode:f.elements.nameMode.value,questionCount:Number(f.elements.questionCount.value),regionCount:Number(f.elements.regionCount.value),bossCount:Number(f.elements.bossCount.value)};try{await api('updateSettings',{settings:s});toast('설정을 저장했습니다.');await loadDashboard(false)}catch(err){showNotice(err.message,true)}});$('#download-csv').addEventListener('click',downloadCsv);$('#open-reset').addEventListener('click',()=>{$('#reset-confirm').value='';$('#reset-dialog').showModal()});$('#reset-form').addEventListener('submit',async e=>{e.preventDefault();if($('#reset-confirm').value!=="RESET")return toast('RESET을 정확히 입력하세요.');try{await api('resetClassData',{className:currentClass,confirmation:'RESET'});$('#reset-dialog').close();toast('수업 결과를 초기화했습니다.');await loadDashboard(false)}catch(err){toast(err.message)}});$$('.dialog-close,.dialog-close-button').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
if(token){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');loadDashboard().then(startRefresh).catch(()=>logout(false))}
